packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@t3-oss/env-nextjs": ^0.11.1
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@types/node": ^22.7.8
  eslint: ^9.9.0
  next: ^15.0.1
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.5.4
  tailwindcss: ^3.4.10
  zod: ^3.23.8

catalogs:
  react:
    "@types/react": npm:types-react@19.0.0-rc.1
    "@types/react-dom": npm:types-react@19.0.0-rc.1
    react: ^19.0.0-rc-69d4b800-20241021
    react-dom: ^19.0.0-rc-69d4b800-20241021
